name: PR Deploy Context
description: Post a PR comment showing which services are affected and how to trigger a staging deploy

inputs:
  repo-name:
    description: "Repository name (e.g. smoltbot, mnemom-api)"
    required: true
  github-token:
    description: "GitHub token with PR write access (use github.token, not app token)"
    required: true

runs:
  using: composite
  steps:
    - name: Analyze PR and post deploy context
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        REPO_NAME: ${{ inputs.repo-name }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GH_REPO: ${{ github.repository }}
      run: |
        echo "Starting deploy context analysis for $REPO_NAME PR #$PR_NUMBER"

        # Get changed files from the PR
        CHANGED_FILES=$(gh pr view "$PR_NUMBER" --repo "$GH_REPO" --json files --jq '.files[].path') || {
          echo "::warning::Could not fetch PR files — skipping deploy context"
          exit 0
        }

        if [ -z "$CHANGED_FILES" ]; then
          echo "No changed files found, skipping"
          exit 0
        fi

        echo "Changed files:"
        echo "$CHANGED_FILES"

        # Map repo -> services based on changed paths
        SERVICES=""
        case "$REPO_NAME" in
          smoltbot)
            HAS_GATEWAY=false
            HAS_OBSERVER=false
            HAS_CLI=false
            while IFS= read -r file; do
              case "$file" in
                gateway/*) HAS_GATEWAY=true ;;
                observer/*) HAS_OBSERVER=true ;;
                cli/*) HAS_CLI=true ;;
                shared/*)
                  HAS_GATEWAY=true
                  HAS_OBSERVER=true
                  HAS_CLI=true
                  ;;
              esac
            done <<< "$CHANGED_FILES"
            [ "$HAS_GATEWAY" = true ] && SERVICES="${SERVICES:+$SERVICES, }gateway"
            [ "$HAS_OBSERVER" = true ] && SERVICES="${SERVICES:+$SERVICES, }observer"
            [ "$HAS_CLI" = true ] && SERVICES="${SERVICES:+$SERVICES, }cli"
            [ -z "$SERVICES" ] && SERVICES="gateway, observer, cli"
            ;;
          mnemom-api) SERVICES="api" ;;
          mnemom-website) SERVICES="website" ;;
          mnemom-reputation)
            HAS_SERVER=false
            HAS_SDK=false
            while IFS= read -r file; do
              case "$file" in
                server/*) HAS_SERVER=true ;;
                client/*) HAS_SDK=true ;;
              esac
            done <<< "$CHANGED_FILES"
            [ "$HAS_SERVER" = true ] && SERVICES="${SERVICES:+$SERVICES, }reputation"
            [ "$HAS_SDK" = true ] && SERVICES="${SERVICES:+$SERVICES, }reputation-sdk"
            [ -z "$SERVICES" ] && SERVICES="reputation, reputation-sdk"
            ;;
          mnemom-risk)
            HAS_SERVER=false
            HAS_SDK=false
            while IFS= read -r file; do
              case "$file" in
                server/*) HAS_SERVER=true ;;
                client/*) HAS_SDK=true ;;
              esac
            done <<< "$CHANGED_FILES"
            [ "$HAS_SERVER" = true ] && SERVICES="${SERVICES:+$SERVICES, }risk"
            [ "$HAS_SDK" = true ] && SERVICES="${SERVICES:+$SERVICES, }risk-sdk"
            [ -z "$SERVICES" ] && SERVICES="risk, risk-sdk"
            ;;
          hunter) SERVICES="hunter" ;;
          *) SERVICES="unknown" ;;
        esac

        echo "Services affected: $SERVICES"

        # Detect shared dependency changes
        SHARED_DEPS=""
        PKG_FILES=$(echo "$CHANGED_FILES" | grep 'package\.json$' || true)
        if [ -n "$PKG_FILES" ]; then
          DEPS_CHANGED=$(gh pr diff "$PR_NUMBER" --repo "$GH_REPO" 2>/dev/null \
            | grep -oE '"@mnemom/[^"]+' | sed 's/"@mnemom\///' | sort -u \
            | tr '\n' ', ' | sed 's/,$//' | sed 's/,/, /g') || true
          [ -n "$DEPS_CHANGED" ] && SHARED_DEPS="$DEPS_CHANGED"
        fi

        # Detect config file changes
        CONFIG_CHANGES=""
        MATCHED_CONFIGS=$(echo "$CHANGED_FILES" \
          | grep -E 'wrangler\.toml|fly\.toml|netlify\.toml|Dockerfile' \
          | xargs -I{} basename {} | sort -u \
          | tr '\n' ', ' | sed 's/,$//' | sed 's/,/, /g') || true
        [ -n "$MATCHED_CONFIGS" ] && CONFIG_CHANGES="$MATCHED_CONFIGS"

        # Build the comment body using a temp file to avoid quoting issues
        BODY_FILE=$(mktemp)
        {
          echo "## Deploy Context"
          echo ""
          echo "| | |"
          echo "|---|---|"
          echo "| **Services affected** | $SERVICES |"
          [ -n "$SHARED_DEPS" ] && echo "| **Shared deps changed** | $SHARED_DEPS |"
          [ -n "$CONFIG_CHANGES" ] && echo "| **Config changes** | $CONFIG_CHANGES |"
          echo ""
          echo "### Staging Deploy"
          echo "After merging, staging deploy triggers automatically."
          echo "Manual trigger: \`gh workflow run deploy.yml --repo mnemom/deploy -f repos=$REPO_NAME -f environment=staging\`"
        } > "$BODY_FILE"

        echo "Comment body:"
        cat "$BODY_FILE"

        # Post or update sticky comment
        gh pr comment "$PR_NUMBER" --repo "$GH_REPO" \
          --body-file "$BODY_FILE" \
          --edit-last 2>/dev/null \
        || gh pr comment "$PR_NUMBER" --repo "$GH_REPO" \
          --body-file "$BODY_FILE"

        rm -f "$BODY_FILE"
        echo "Deploy context comment posted successfully"
